services:
  backend:
    build:
      context: ./backend
    container_name: nextstop-backend
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      args:
        EXPO_PUBLIC_API_URL: http://20.220.169.175:3000
    container_name: nextstop-frontend
    depends_on:
      - backend
    ports:
      - "80:80"
    restart: unless-stopped